DROP TABLE IF EXISTS `FILE_MESSAGE`;
DROP TABLE IF EXISTS `MESSAGE_CHATNUM`;
DROP TABLE IF EXISTS `CHAT_USERS`;
DROP TABLE IF EXISTS `CHAT`;
DROP TABLE IF EXISTS `FILE_DRIVE`;
DROP TABLE IF EXISTS `GROUP`;
DROP TABLE IF EXISTS `TEAM_LIST`;
DROP TABLE IF EXISTS `SCHEDULE`;
DROP TABLE IF EXISTS `MEMBER_WITHDRAWAL`;
DROP TABLE IF EXISTS `FILE_DOC`;
DROP TABLE IF EXISTS `DOC_APPROVAL`;
DROP TABLE IF EXISTS `DOC_REFERRER`;
DROP TABLE IF EXISTS `DOC`;
DROP TABLE IF EXISTS `DOC_APPROVAL_DEFAULT`;
DROP TABLE IF EXISTS `DOC_LIST`;
DROP TABLE IF EXISTS `MEMBER_DETAILS`;
DROP TABLE IF EXISTS `KIWI_KEY`;
DROP TABLE IF EXISTS `COMPANY`;
DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `MEMBER` (
	`MEMBER_ID` VARCHAR(320) NOT NULL COMMENT 'UNIQUE/회원아이디 최소10',
	`MEMBER_PW` VARCHAR(80) NOT NULL COMMENT '회원비밀번호',
	`MEMBER_DATE` DATETIME NOT NULL DEFAULT (CURRENT_DATE) COMMENT '회원가입일자',
	`MEMBER_FILEPATH` VARCHAR(1000) NULL COMMENT '프로필사진 파일경로 / 예시)C:\workspace\KIWI\files',
	`MEMBER_STATUS` BOOLEAN NOT NULL DEFAULT 1 COMMENT '활동(1), 잠금(0)',
	`EXPIRE_DATE` DATE NULL COMMENT '!!(보류)//SYSDATE+1YEAR',
	`MEMBER_ROLE` VARCHAR(6) NOT NULL DEFAULT 'MEMBER' COMMENT '회원(MEMBER),잔디관리자(KADMIN)',
	`MEMBER_NICKNAME` VARCHAR(30) NOT NULL COMMENT '닉네임'
);

CREATE TABLE `COMPANY` (
	`COMPANY_NUM` INT NOT NULL COMMENT 'UNIQUE/회사번호',
	`COMPANY` VARCHAR(100) NOT NULL COMMENT '회사명'
);

CREATE TABLE `KIWI_KEY` (
	`COM_EMP_NUM` VARCHAR(40) NOT NULL COMMENT '_ 사용하여 만듬, KIWI내부사용ID',
	`COMPANY_NUM` INT NOT NULL COMMENT 'UNIQUE/회사번호',
	`EMPLOYEE_NUM` VARCHAR(40) NOT NULL COMMENT '회사가 지정함'
);

CREATE TABLE `MEMBER_DETAILS` (
	`COM_EMP_NUM` VARCHAR(40) NOT NULL COMMENT '_ 사용하여 만듬, KIWI내부사용ID',
	`MEMBER_ID` VARCHAR(320) NOT NULL COMMENT 'UNIQUE/회원아이디',
	`COMPANY` VARCHAR(100) NOT NULL COMMENT 'UNUQUE/회사명',
	`NAME` VARCHAR(20) NOT NULL COMMENT 'UNUQUE/사원이름',
	`GENDER` CHAR(1) NULL COMMENT '성별/남자(0),여자(1)',
	`BIRTH_DATE` DATE NULL COMMENT '생년월일',
	`EMP_DATE` DATE NOT NULL COMMENT '입사일자(DATE_OF_EMPLOYMENT)',
	`QUIT_DATE` DATE NULL COMMENT '퇴사일자(DATE_OF_RESIGNATION)',
	`PHONE` INT NULL COMMENT '연락처',
	`ADDRESS` VARCHAR(50) NULL COMMENT '주소',
	`DEPT_NUM` INT NULL COMMENT '부서코드',
	`TITLE` VARCHAR(10) NULL COMMENT '예)인턴,사원,주임,대리,과장,차장,부장,상무,전무,사장 등',
	`POSITION` VARCHAR(10) NULL COMMENT '예)파트장,팀장,실장,본부장, 대표이사 등',
	`DOC_SECURITY` CHAR(1) NOT NULL DEFAULT 9 COMMENT '보안등급레벨 0~9 / 9가 낮은등급',
	`DAY_OFF` INT NULL COMMENT '잔여 휴가일수',
	`USED_DAY_OFF` DOUBLE NULL COMMENT '사용 휴가일수 / 반차 0.5 차감'
);

CREATE TABLE `DOC_LIST` (
	`DOC_TYPE` VARCHAR(50) NOT NULL COMMENT '연차,월차, 지출내역서, 품의서, 기안서,시말서, 사직서...',
	`COMPANY_NUM` INT NOT NULL COMMENT 'UNIQUE/회사번호',
	`DOC_CONTENT` VARCHAR(5000) NULL COMMENT 'aaa.thml, bbb.html'
);

CREATE TABLE `DOC_APPROVAL_DEFAULT` (
	`DOC_TYPE` VARCHAR(50) NOT NULL COMMENT '연차,월차, 지출내역서, 품의서, 기안서,시말서, 사직서...',
	`COMPANY_NUM` INT NOT NULL COMMENT 'UNIQUE/회사번호',
	`APR_COM_EMP_NUM` VARCHAR(40) NOT NULL COMMENT '_결재자 사용하여 만듬, KIWI내부사용ID'
);

CREATE TABLE `DOC` (
	`DOC_NUM` INT NOT NULL COMMENT 'UNIQUE/서류번호',
	`CRE_COM_EMP_NUM` VARCHAR(40) NOT NULL COMMENT '작성자_ 사용하여 만듬, KIWI내부사용ID',
	`DOC_TITLE` VARCHAR(50) NOT NULL,
	`DOC_DATE` DATE NOT NULL,
	`DOC_SECURITY` CHAR(1) NOT NULL DEFAULT 9 COMMENT '보안등급레벨 0~9 / 9가 낮은등급',
	`DOC_TYPE` VARCHAR(50) NOT NULL COMMENT '연차,월차, 지출내역서, 품의서, 기안서,시말서, 사직서...'
);

CREATE TABLE `DOC_REFERRER` (
	`COM_EMP_NUM` VARCHAR(40) NOT NULL COMMENT '_ 사용하여 만듬, KIWI내부사용ID',
	`DOC_NUM` INT NOT NULL COMMENT 'UNIQUE/서류번호',
	`CRE_COM_EMP_NUM` VARCHAR(40) NOT NULL COMMENT '작성자_ 사용하여 만듬, KIWI내부사용ID'
);

CREATE TABLE `DOC_APPROVAL` (
	`DOC_SEQ` CHAR(2) NOT NULL COMMENT '1,2,3 (check  between 1 and 5))',
	`APR_COM_EMP_NUM` VARCHAR(40) NOT NULL COMMENT '결재자',
	`DOC_NUM` INT NOT NULL COMMENT 'UNIQUE/서류번호',
	`CRE_COM_EMP_NUM` VARCHAR(40) NOT NULL COMMENT '작성자',
	`DOC_CONF` CHAR(1) NOT NULL DEFAULT 0 COMMENT '대기(0),승인(1), 거절(2)',
	`DOC_REJECT` VARCHAR(1000) NULL
);

CREATE TABLE `FILE_DOC` (
	`FILE_CODE` INT NOT NULL COMMENT 'UNIQUE/파일번호(비공개)/서버식별용(JAVA UUID)',
	`DOC_NUM` INT NOT NULL COMMENT 'UNIQUE/서류번호',
	`CRE_COM_EMP_NUM` VARCHAR(40) NOT NULL COMMENT '_ 사용하여 만듬, KIWI내부사용ID',
	`FILE_NAME` VARCHAR(1000) NULL COMMENT '유저가 설정한 파일이름',
	`FILE_PATH` VARCHAR(1000) NULL COMMENT '파일경로 / 예시)C:\workspace\KIWI\files',
	`UPLOAD_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '업로드한 시간'
);

CREATE TABLE `MEMBER_WITHDRAWAL` (
	`MEMBER_ID` VARCHAR(320) NOT NULL COMMENT 'UNIQUE/회원아이디',
	`MEMBER_PW` VARCHAR(80) NOT NULL COMMENT '회원비밀번호',
	`MEMBER_DATE` DATETIME NOT NULL DEFAULT (CURRENT_DATE) COMMENT '회원가입일자',
	`MEMBER_FILEPATH` VARCHAR(1000) NULL COMMENT '프로필사진 파일경로 / 예시)C:\workspace\KIWI\files',
	`MEMBER_STATUS` BOOLEAN NOT NULL DEFAULT 0 COMMENT '활동(1), 잠금(0)',
	`EXPIRE_DATE` DATE NULL COMMENT '!!(보류)//SYSDATE+1YEAR',
	`MEMBER_ROLE` VARCHAR(6) NOT NULL DEFAULT 'MEMBER' COMMENT '회원(MEMBER),잔디관리자(KADMIN)',
	`MEMBER_NICKNAME` VARCHAR(30) NOT NULL COMMENT '닉네임'
);

CREATE TABLE `SCHEDULE` (
	`SCHEDULE` INT NOT NULL COMMENT 'UNIQUE/일정번호(비공개)',
	`MEMBER_ID` VARCHAR(320) NOT NULL COMMENT 'UNIQUE/회원아이디',
	`SCHEDULE_DATE` DATETIME NOT NULL DEFAULT (CURRENT_DATE) COMMENT '일정 날짜와 시간',
	`SCHEDULE_NAME` VARCHAR(30) NOT NULL COMMENT '일정이름',
	`SCHEDULE_CONTENT` VARCHAR(1000) NULL COMMENT '일정설명'
);

CREATE TABLE `TEAM_LIST` (
	`TEAM` VARCHAR(15) NOT NULL COMMENT '20240528_000001',
	`TEAM_NAME` VARCHAR(100) NOT NULL,
	`TEAM_ADMIN_MEMBER_ID` VARCHAR(320) NOT NULL COMMENT '팀생성한 회원이 관리자'
);

CREATE TABLE `GROUP` (
	`MEMBER_ID` VARCHAR(320) NOT NULL COMMENT '회원아이디',
	`TEAM` VARCHAR(15) NOT NULL COMMENT '20240528_000001'
);

CREATE TABLE `FILE_DRIVE` (
	`FILE_CODE` VARCHAR(50) NOT NULL COMMENT 'UNIQUE/파일번호(비공개)/서버식별용(JAVA UUID)',
	`TEAM` VARCHAR(15) NOT NULL COMMENT '20240528_000001',
	`FILE_NAME` VARCHAR(1000) NOT NULL COMMENT '유저가 설정한 파일이름',
	`FILE_PATH` VARCHAR(1000) NULL COMMENT '파일경로 / 예시)C:\workspace\KIWI\files',
	`UPLOAD_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '업로드한 시간'
);

CREATE TABLE `CHAT` (
	`CHAT_NUM` INT NOT NULL COMMENT 'UNIQUE/채팅방번호(비공개)',
	`CHAT_NAME` VARCHAR(30) NOT NULL COMMENT '채팅방이름',
	`CHAT_OPEN` BOOLEAN NOT NULL DEFAULT 0 COMMENT '공개(1),비공개(0)',
	`CHAT_ADMIN_MEMBER_ID` VARCHAR(320) NOT NULL COMMENT '채팅방 관리자 MEMBER_ID',
	`TEAM` VARCHAR(15) NOT NULL COMMENT '20240528_000001'
);

CREATE TABLE `CHAT_USERS` (
	`CHAT_NUM` INT NOT NULL COMMENT 'UNIQUE/채팅방번호(비공개)',
	`MEMBER_ID` VARCHAR(320) NOT NULL COMMENT 'UNIQUE/회원아이디 최소10',
	`CHAT_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	`CHAT_ADMIN` INT NOT NULL DEFAULT 0 COMMENT '생성자 1, 관리자 2, 일반 0'
);

CREATE TABLE `MESSAGE_CHATNUM` (
	`MESSAGE_NUM` INT NOT NULL COMMENT '채팅시간+번호(같은채팅시간이 있다면 1,2,3) 예2024052815301234562',
	`CHAT_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '채팅한 시간',
	`CHAT_NUM` INT NOT NULL COMMENT 'UNIQUE/채팅방번호(비공개)',
	`MEMBER_ID` VARCHAR(320) NOT NULL COMMENT 'UNIQUE/회원아이디 최소10',
	`CHAT_CONTENT` VARCHAR(5000) NULL COMMENT '채팅내용  ftp://파일경로',
	`READ_COUNT` INT NULL COMMENT '모두 읽었을시 카운트표기없음, 읽지않은 인원수 카운트',
	`CHAT_CHECK` BOOLEAN NULL COMMENT '- 체크상태',
	`CHAT_REF` BOOLEAN NOT NULL DEFAULT 0 COMMENT '원글(0),댓글(1), 대댓글없음',
	`CHAT_REF_MESSAGE_NUM` INT NULL DEFAULT NULL COMMENT '댓글_채팅시간+번호(같은채팅시간이 있다면 1,2,3) 예2024052815301234562',
	`CHAT_REF_CHAT_TIME` DATETIME NULL DEFAULT NULL COMMENT '댓글_채팅한 시간'
);

CREATE TABLE `FILE_MESSAGE` (
	`FILE_CODE` VARCHAR(50) NOT NULL COMMENT 'UNIQUE/파일번호(비공개)/서버식별용(JAVAUUID)',
	`MESSAGE_NUM` INT NOT NULL COMMENT '채팅시간+번호(같은채팅시간이 있다면 1,2,3) 예2024052815301234562',
	`CHAT_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '채팅한 시간',
	`FILE_NAME` VARCHAR(1000) NOT NULL COMMENT '유저가 설정한 파일이름',
	`FILE_PATH` VARCHAR(1000) NULL COMMENT '파일경로 / 예시)C:\workspace\KIWI\files',
	`UPLOAD_TIME` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '업로드한 시간'
);

ALTER TABLE `GROUP` ADD CONSTRAINT `PK_GROUP` PRIMARY KEY (
	`MEMBER_ID`,
	`TEAM`
);

ALTER TABLE `CHAT` ADD CONSTRAINT `PK_CHAT` PRIMARY KEY (`CHAT_NUM`);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (`MEMBER_ID`);

ALTER TABLE `MESSAGE_CHATNUM` ADD CONSTRAINT `PK_MESSAGE_CHATNUM` PRIMARY KEY (
	`MESSAGE_NUM`,
	`CHAT_TIME`
);

ALTER TABLE `SCHEDULE` ADD CONSTRAINT `PK_SCHEDULE` PRIMARY KEY (`SCHEDULE`);

ALTER TABLE `FILE_DRIVE` ADD CONSTRAINT `PK_FILE_DRIVE` PRIMARY KEY (
	`FILE_CODE`,
	`TEAM`
);

ALTER TABLE `FILE_MESSAGE` ADD CONSTRAINT `PK_FILE_MESSAGE` PRIMARY KEY (
	`FILE_CODE`,
	`MESSAGE_NUM`,
	`CHAT_TIME`
);

ALTER TABLE `MEMBER_DETAILS` ADD CONSTRAINT `PK_MEMBER_DETAILS` PRIMARY KEY (`COM_EMP_NUM`);

ALTER TABLE `DOC` ADD CONSTRAINT `PK_DOC` PRIMARY KEY (
	`DOC_NUM`,
	`CRE_COM_EMP_NUM`
);

ALTER TABLE `FILE_DOC` ADD CONSTRAINT `PK_FILE_DOC` PRIMARY KEY (
	`FILE_CODE`,
	`DOC_NUM`,
	`CRE_COM_EMP_NUM`
);

ALTER TABLE `CHAT_USERS` ADD CONSTRAINT `PK_CHAT_USERS` PRIMARY KEY (
	`CHAT_NUM`,
	`MEMBER_ID`
);

ALTER TABLE `COMPANY` ADD CONSTRAINT `PK_COMPANY` PRIMARY KEY (`COMPANY_NUM`);

ALTER TABLE `DOC_APPROVAL` ADD CONSTRAINT `PK_DOC_APPROVAL` PRIMARY KEY (
	`DOC_SEQ`,
	`APR_COM_EMP_NUM`,
	`DOC_NUM`,
	`CRE_COM_EMP_NUM`
);

ALTER TABLE `DOC_REFERRER` ADD CONSTRAINT `PK_DOC_REFERRER` PRIMARY KEY (
	`COM_EMP_NUM`,
	`DOC_NUM`,
	`CRE_COM_EMP_NUM`
);

ALTER TABLE `DOC_LIST` ADD CONSTRAINT `PK_DOC_LIST` PRIMARY KEY (
	`DOC_TYPE`,
	`COMPANY_NUM`
);

ALTER TABLE `TEAM_LIST` ADD CONSTRAINT `PK_TEAM_LIST` PRIMARY KEY (`TEAM`);

ALTER TABLE `MEMBER_WITHDRAWAL` ADD CONSTRAINT `PK_MEMBER_WITHDRAWAL` PRIMARY KEY (`MEMBER_ID`);

ALTER TABLE `KIWI_KEY` ADD CONSTRAINT `PK_KIWI_KEY` PRIMARY KEY (`COM_EMP_NUM`);

ALTER TABLE `GROUP` ADD CONSTRAINT `FK_MEMBER_TO_GROUP_1` FOREIGN KEY (`MEMBER_ID`)
REFERENCES `MEMBER` (`MEMBER_ID`);

ALTER TABLE `GROUP` ADD CONSTRAINT `FK_TEAM_LIST_TO_GROUP_1` FOREIGN KEY (`TEAM`)
REFERENCES `TEAM_LIST` (`TEAM`);

ALTER TABLE `SCHEDULE` ADD CONSTRAINT `FK_MEMBER_TO_SCHEDULE_1` FOREIGN KEY (`MEMBER_ID`)
REFERENCES `MEMBER` (`MEMBER_ID`);

ALTER TABLE `MEMBER_DETAILS` ADD CONSTRAINT `FK_KIWI_KEY_TO_MEMBER_DETAILS_1` FOREIGN KEY (`COM_EMP_NUM`)
REFERENCES `KIWI_KEY` (`COM_EMP_NUM`);

ALTER TABLE `MEMBER_DETAILS` ADD CONSTRAINT `FK_MEMBER_TO_MEMBER_DETAILS_1` FOREIGN KEY (`MEMBER_ID`)
REFERENCES `MEMBER` (`MEMBER_ID`);

ALTER TABLE `DOC` ADD CONSTRAINT `FK_MEMBER_DETAILS_TO_DOC_1` FOREIGN KEY (`CRE_COM_EMP_NUM`)
REFERENCES `MEMBER_DETAILS` (`COM_EMP_NUM`);

ALTER TABLE `DOC_REFERRER` ADD CONSTRAINT `FK_MEMBER_DETAILS_TO_DOC_REFERRER_1` FOREIGN KEY (`COM_EMP_NUM`)
REFERENCES `MEMBER_DETAILS` (`COM_EMP_NUM`);

ALTER TABLE `DOC_LIST` ADD CONSTRAINT `FK_COMPANY_TO_DOC_LIST_1` FOREIGN KEY (`COMPANY_NUM`)
REFERENCES `COMPANY` (`COMPANY_NUM`);

ALTER TABLE `DOC_APPROVAL_DEFAULT` ADD CONSTRAINT `FK_MEMBER_DETAILS_TO_DOC_APPROVAL_DEFAULT_1` FOREIGN KEY (`APR_COM_EMP_NUM`)
REFERENCES `MEMBER_DETAILS` (`COM_EMP_NUM`);

ALTER TABLE `TEAM_LIST` ADD CONSTRAINT `FK_MEMBER_TO_TEAM_LIST_1` FOREIGN KEY (`TEAM_ADMIN_MEMBER_ID`)
REFERENCES `MEMBER` (`MEMBER_ID`);

ALTER TABLE `MEMBER_WITHDRAWAL` ADD CONSTRAINT `FK_MEMBER_TO_MEMBER_WITHDRAWAL_1` FOREIGN KEY (`MEMBER_ID`)
REFERENCES `MEMBER` (`MEMBER_ID`);

ALTER TABLE `KIWI_KEY` ADD CONSTRAINT `FK_COMPANY_TO_KIWI_KEY_1` FOREIGN KEY (`COMPANY_NUM`)
REFERENCES `COMPANY` (`COMPANY_NUM`);

ALTER TABLE `CHAT_USERS` ADD CONSTRAINT `FK_CHAT_TO_CHAT_USERS_1` FOREIGN KEY (`CHAT_NUM`)
REFERENCES `CHAT` (`CHAT_NUM`);

ALTER TABLE `CHAT_USERS` ADD CONSTRAINT `FK_MEMBER_TO_CHAT_USERS_1` FOREIGN KEY (`MEMBER_ID`)
REFERENCES `MEMBER` (`MEMBER_ID`);

ALTER TABLE `DOC_APPROVAL` ADD CONSTRAINT `FK_MEMBER_DETAILS_TO_DOC_APPROVAL_1` FOREIGN KEY (`APR_COM_EMP_NUM`)
REFERENCES `MEMBER_DETAILS` (`COM_EMP_NUM`);

ALTER TABLE `GROUP`
ADD CONSTRAINT `UNIQUE_MEMBER_ID` UNIQUE (`MEMBER_ID`);

ALTER TABLE `CHAT`
ADD CONSTRAINT `FK_GROUP_TO_CHAT_1` FOREIGN KEY (`CHAT_ADMIN_MEMBER_ID`)
REFERENCES `GROUP` (`MEMBER_ID`);

ALTER TABLE `CHAT` ADD CONSTRAINT `FK_GROUP_TO_CHAT_10` FOREIGN KEY (`CHAT_ADMIN_MEMBER_ID`)
REFERENCES `GROUP` (`MEMBER_ID`);

ALTER TABLE `GROUP`
ADD CONSTRAINT `UNIQUE_TEAM` UNIQUE (`TEAM`);

ALTER TABLE `CHAT`
ADD CONSTRAINT `FK_GROUP_TO_CHAT_20` FOREIGN KEY (`TEAM`)
REFERENCES `GROUP` (`TEAM`);

ALTER TABLE `CHAT` ADD CONSTRAINT `FK_GROUP_TO_CHAT_11` FOREIGN KEY (`TEAM`)
REFERENCES `GROUP` (`TEAM`);

ALTER TABLE `CHAT_USERS`
ADD CONSTRAINT `UNIQUE_CHAT_NUM` UNIQUE (`CHAT_NUM`);

ALTER TABLE `MESSAGE_CHATNUM` ADD CONSTRAINT `FK_CHAT_USERS_TO_MESSAGE_CHATNUM_1` FOREIGN KEY (`CHAT_NUM`)
REFERENCES `CHAT_USERS` (`CHAT_NUM`);

ALTER TABLE `CHAT_USERS`
ADD CONSTRAINT `UNIQUE_MEMBER_ID` UNIQUE (`MEMBER_ID`);

ALTER TABLE `MESSAGE_CHATNUM` ADD CONSTRAINT `FK_CHAT_USERS_TO_MESSAGE_CHATNUM_2` FOREIGN KEY (`MEMBER_ID`)
REFERENCES `CHAT_USERS` (`MEMBER_ID`);

ALTER TABLE `MESSAGE_CHATNUM`
ADD CONSTRAINT `UNIQUE_MESSAGE_NUM` UNIQUE (`MESSAGE_NUM`);

ALTER TABLE `MESSAGE_CHATNUM` ADD CONSTRAINT `FK_MESSAGE_CHATNUM_TO_MESSAGE_CHATNUM_1` FOREIGN KEY (`CHAT_REF_MESSAGE_NUM`)
REFERENCES `MESSAGE_CHATNUM` (`MESSAGE_NUM`);

ALTER TABLE `MESSAGE_CHATNUM`
ADD CONSTRAINT `UNIQUE_CHAT_TIME` UNIQUE (`CHAT_TIME`);

ALTER TABLE `MESSAGE_CHATNUM` ADD CONSTRAINT `FK_MESSAGE_CHATNUM_TO_MESSAGE_CHATNUM_2` FOREIGN KEY (`CHAT_REF_CHAT_TIME`)
REFERENCES `MESSAGE_CHATNUM` (`CHAT_TIME`);

ALTER TABLE `FILE_DRIVE` ADD CONSTRAINT `FK_GROUP_TO_FILE_DRIVE_1` FOREIGN KEY (`TEAM`)
REFERENCES `GROUP` (`TEAM`);

ALTER TABLE `FILE_MESSAGE` ADD CONSTRAINT `FK_MESSAGE_CHATNUM_TO_FILE_MESSAGE_1` FOREIGN KEY (`MESSAGE_NUM`)
REFERENCES `MESSAGE_CHATNUM` (`MESSAGE_NUM`);

ALTER TABLE `FILE_MESSAGE` ADD CONSTRAINT `FK_MESSAGE_CHATNUM_TO_FILE_MESSAGE_2` FOREIGN KEY (`CHAT_TIME`)
REFERENCES `MESSAGE_CHATNUM` (`CHAT_TIME`);

ALTER TABLE `DOC_LIST`
ADD CONSTRAINT `UNIQUE_DOC_TYPE` UNIQUE (`DOC_TYPE`);

ALTER TABLE `DOC` ADD CONSTRAINT `FK_DOC_LIST_TO_DOC_1` FOREIGN KEY (`DOC_TYPE`)
REFERENCES `DOC_LIST` (`DOC_TYPE`);

ALTER TABLE `DOC`
ADD CONSTRAINT `UNIQUE_DOC_NUM` UNIQUE (`DOC_NUM`);

ALTER TABLE `FILE_DOC` ADD CONSTRAINT `FK_DOC_TO_FILE_DOC_1` FOREIGN KEY (`DOC_NUM`)
REFERENCES `DOC` (`DOC_NUM`);

ALTER TABLE `DOC`
ADD CONSTRAINT `UNIQUE_CRE_COM_EMP_NUM` UNIQUE (`CRE_COM_EMP_NUM`);

ALTER TABLE `FILE_DOC` ADD CONSTRAINT `FK_DOC_TO_FILE_DOC_2` FOREIGN KEY (`CRE_COM_EMP_NUM`)
REFERENCES `DOC` (`CRE_COM_EMP_NUM`);

ALTER TABLE `DOC_APPROVAL` ADD CONSTRAINT `FK_DOC_TO_DOC_APPROVAL_1` FOREIGN KEY (`DOC_NUM`)
REFERENCES `DOC` (`DOC_NUM`);

ALTER TABLE `DOC_APPROVAL` ADD CONSTRAINT `FK_DOC_TO_DOC_APPROVAL_2` FOREIGN KEY (`CRE_COM_EMP_NUM`)
REFERENCES `DOC` (`CRE_COM_EMP_NUM`);

ALTER TABLE `DOC_REFERRER` ADD CONSTRAINT `FK_DOC_TO_DOC_REFERRER_1` FOREIGN KEY (`DOC_NUM`)
REFERENCES `DOC` (`DOC_NUM`);

ALTER TABLE `DOC_REFERRER` ADD CONSTRAINT `FK_DOC_TO_DOC_REFERRER_2` FOREIGN KEY (`CRE_COM_EMP_NUM`)
REFERENCES `DOC` (`CRE_COM_EMP_NUM`);

ALTER TABLE `DOC_APPROVAL_DEFAULT` ADD CONSTRAINT `FK_DOC_LIST_TO_DOC_APPROVAL_DEFAULT_1` FOREIGN KEY (`DOC_TYPE`)
REFERENCES `DOC_LIST` (`DOC_TYPE`);

ALTER TABLE `DOC_LIST`
ADD CONSTRAINT `UNIQUE_COMPANY_NUM` UNIQUE (`COMPANY_NUM`);

ALTER TABLE `DOC_APPROVAL_DEFAULT` ADD CONSTRAINT `FK_DOC_LIST_TO_DOC_APPROVAL_DEFAULT_2` FOREIGN KEY (`COMPANY_NUM`)
REFERENCES `DOC_LIST` (`COMPANY_NUM`);